### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by map0logo** [ErudioOne/PyTorch#1]
For branding, I think it basically just means to stick the logo at https://erudio.one/wp-content/uploads/2023/11/logo-2048x692.png at the top of each notebook. But obviously, we need to remove any mention of other contexts/clients where I might have taught the materials previously. I'm not sure if any are there, but maybe. And some links, installed software versions, etc should be updated (we'd like to use the most recent version of all libraries and Python version possible for each course).

**Comment by DavidMertz** [comment]
There are quite a few mentions of the repo where the material was taken from, and also some of my other personal company KDM Training.  Those should all get updated to say Erudio/this repo.  And for now, we're under the more restrictive CC BY-NC-ND 4.0, rather than the CC BY-NC-SA 4.0 that is mentioned in the content (obviously, the someone *could* go find the slightly more liberal license version at the other repo).
